### ISSUE TITLE
reviewsCount is missing for some places

### ISSUE THREAD

**Issue by metalwarrior665** [drobnikj/crawler-google-places#18]
Reviews are on the page
https://my.apify.com/view/runs/zjXGQcpdyfipKrK57

**Comment by joelbqz** [comment]
Hello @drobnikj I did forked the repository and fixed this issue on my side locally, I think the issue is here:

file: `/src/places_crawler.js`

I changed the regular expression:
![image](https://user-images.githubusercontent.com/19965325/70474469-a85d5580-1aa0-11ea-98c0-1aa4961e1e73.png)

I suck using git, and I'm not familiar doing pull requests, also maybe my regular expression is not very optimal, but that fixed the issue I had, and could give you an insight on how to fix it and come with an optimal solution.

**Comment by drobnikj** [comment]
@joelbqz Thanks for regexp!
I fixed it with a simple one, it should work.
