### ISSUE TITLE
[QUESTION] How to run it on my computer ?

### ISSUE THREAD

**Issue by ti3059** [drobnikj/crawler-google-places#36]
Hello,

Could you tell me how should I do to run it on my computer please ?

thank you

**Comment by rockiniowa** [comment]
I am not sure how to do this either.  I hope others will help.  But I am in the process of learning too. 
I hope somebody else answers.  I wanna know too.

Meanwhile see these links:
https://help.apify.com/en/articles/1760950-develop-build-and-run-actors-locally-using-the-apify-command-line-client (an idea of how to get you stated with prerequired software)

https://docs.apify.com/cli#installation (about command in line interface).

and...

https://apify.com/drobnikj/crawler-google-places?section=how-to-run (how to run an actor or app, but not necessarily this same app).

**Comment by metalwarrior665** [comment]
Sorry guys for a late reply. Every Apify actor can be technically run locally. 
- Clone this repo
- Install the [Apify CLI](https://github.com/apifytech/apify-cli)
- Optionally login to your Apify account
- `npm install` everything
- run with `apify run -p`

It might complain that you don't have access to Apify proxy. This is unfortunately there so that Google doesn't report our servers. You can disable it if you find the line of code where this check is :)
